######################## default configuration ####################
baseURL = "https://about.pally.in"
languageCode = "en-us"
title = "Gosaas | hugo saas landing template"
theme = "gosaas-hugo"
publishDir = "docs"

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"

  
############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Service"
  URL = "service"
  weight = 3
  
  [[menu.main]]
  name = "Team"
  URL = "team"
  weight = 4
  
  [[menu.main]]
  name = "Pricing"
  URL = "pricing"
  weight = 5
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 6
  
  ###################### footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.footer]]
  name = "Service"
  URL = "service"
  weight = 3
  
  [[menu.footer]]
  name = "Team"
  URL = "team"
  weight = 4
  
  [[menu.footer]]
  name = "Pricing"
  URL = "pricing"
  weight = 5
    
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 6


#################### default parameters ################################
[params]
logo = "images/pally_3.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# copyright
copyright = "| @2019 [Themefisher](https://themefisher.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # Navigation get start button
  [params.navButton]
  enable = true
  label = "Get A Quote"
  link = "contact"


############################### social links ############################
[[params.social]]
name = "Facebook"
link = "#"

[[params.social]]
name = "Twitter"
link = "https://twitter.com/pally_in"

[[params.social]]
name = "Github"
link = "https://github.com/PallyIn/"

[[params.social]]
name = "Linkedin"
link = "#"


########################### footer call to action #####################
[params.cta]
enable = true
title  = "Join so many growing businesses like you that <br> use Pally to build trust with their users"
#button
label = "Get start with us"
link = "#"


############################ footer ##############################
[params.footer]
bgImage = "images/backgrounds/footer-bg.png"
content = "We help you trust your customer"

# card we accept
#[[params.footer.card]]
#image = "images/paypal.png"
#[[params.footer.card]]
#image = "images/visa.png"
#[[params.footer.card]]
#image = "images/a-express.png"
